version: '3.8'
services:
    # mongo:
    #     image: mongo
    #     container_name: mongo_container
    #     ports:
    #         - '27017:27017'
    #     logging:
    #         driver: none
            
    server:
        build: './packages/server'
        container_name: server_container
        ports:
            - '3000:3000'
        volumes:
            - './packages/server:/app'
            - '/app/node_modules'
            
        

    client:
        build: './packages/client'
        container_name: client_container
        ports:
            - '5173:5173'
        volumes:
            - './packages/client:/app'
            - '/app/node_modules'
        depends_on:
            - server
        stdin_open: true
        tty: true
